// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9JW9KDdwQ7MVCubh302GWiKOlXDAFI_4',
    appId: '1:592727750264:android:f8e7f904fbf642de9fdf8d',
    messagingSenderId: '592727750264',
    projectId: 'mynewnote-hemmyh',
    storageBucket: 'mynewnote-hemmyh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0YQ3cgNpNELPjGoxEqdPJCaWtdzNEuOc',
    appId: '1:592727750264:ios:a0c66e44d5b0fff09fdf8d',
    messagingSenderId: '592727750264',
    projectId: 'mynewnote-hemmyh',
    storageBucket: 'mynewnote-hemmyh.appspot.com',
    iosClientId: '592727750264-q1mg3g36vnhv26hamb2ios0kckjnfl4n.apps.googleusercontent.com',
    iosBundleId: 'com.hemmyhios.note',
  );
}
